// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace BaseProject.Identity.Migrations
{
    public partial class AddedPincode : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "PinCode",
                table: "AspNetUsers",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "PinCodeAttempts",
                table: "AspNetUsers",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<DateTime>(
                name: "PinCodeGeneration",
                table: "AspNetUsers",
                type: "datetime2",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "PinCode",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "PinCodeAttempts",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "PinCodeGeneration",
                table: "AspNetUsers");
        }
    }
}
