name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore BaseProject/
    - name: Build
      run: dotnet build BaseProject/BaseProject.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test BaseProject/BaseProject.sln --no-restore --verbosity normal
